version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: diary_app-db-1
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
    - "3000:3000" # ホストとコンテナのポートをマッピング
    env_file:
      - .env