version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    env_file:
      - .env

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      - db
    env_file:
      - .env