services:
  db:
    image: mysql:8.0
    container_name: diary_app-db-1
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - diary_app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT:-3000}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - diary_app_network

volumes:
  db_data:

networks:
  diary_app_network:
    driver: bridge
