default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USER", "your_username") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "your_password") %>
  database: <%= ENV.fetch("POSTGRES_DB", "app_development") %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_production") %>