default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER") { "root" } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("MYSQL_HOST") { "db" } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %> # ポートを追加

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") %>

test:
  <<: *default
  database: diary_app_test

production:
  <<: *default
  database: <%= ENV["MYSQL_DATABASE"] %>