default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development:
  <<: *default
  database: diary_app_development
  username: root
  password: 'MySecurePass2024!'  # ここに設定したパスワードを確認
  host: db
  port: 3306

test:
  <<: *default
  database: diary_app_test
  username: root
  password: 'MySecurePass2024!'  # ここに設定したパスワードを入力
  host: db 
  port: 3306

production:
  <<: *default
  database: diary_app_production
  username: diary_app
  password: <%= ENV['MYSQL_PASSWORD'] %>